name: swapio
description: Plantilla base de la aplicación Flutter Swapio.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  connectivity_plus: ^6.0.3  # Para detectar si hay internet (Escenario Offline)
  fl_chart: ^0.68.0          # Para los gráficos de los reportes (BQ)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
