// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6EbQcR8FZn21B9o1qRNw22BzKwXH36K0',
    appId: '1:259265846742:web:111d0f9dc645fabb5f5877',
    messagingSenderId: '259265846742',
    projectId: 'swapp-io-aa00d',
    authDomain: 'swapp-io-aa00d.firebaseapp.com',
    databaseURL: 'https://swapp-io-aa00d-default-rtdb.firebaseio.com',
    storageBucket: 'swapp-io-aa00d.firebasestorage.app',
    measurementId: 'G-KSF0LDH3YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY2fpEbpsNPs9yyXVdFfKHVAbxSPgL63s',
    appId: '1:259265846742:android:7d9895004cc38c445f5877',
    messagingSenderId: '259265846742',
    projectId: 'swapp-io-aa00d',
    databaseURL: 'https://swapp-io-aa00d-default-rtdb.firebaseio.com',
    storageBucket: 'swapp-io-aa00d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ2lWoVYXzWQ3Iyxv-xFJiRo8jlh8Zghs',
    appId: '1:259265846742:ios:81ea2e608fd4b8535f5877',
    messagingSenderId: '259265846742',
    projectId: 'swapp-io-aa00d',
    databaseURL: 'https://swapp-io-aa00d-default-rtdb.firebaseio.com',
    storageBucket: 'swapp-io-aa00d.firebasestorage.app',
    iosBundleId: 'com.example.swappio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ2lWoVYXzWQ3Iyxv-xFJiRo8jlh8Zghs',
    appId: '1:259265846742:ios:81ea2e608fd4b8535f5877',
    messagingSenderId: '259265846742',
    projectId: 'swapp-io-aa00d',
    databaseURL: 'https://swapp-io-aa00d-default-rtdb.firebaseio.com',
    storageBucket: 'swapp-io-aa00d.firebasestorage.app',
    iosBundleId: 'com.example.swappio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6EbQcR8FZn21B9o1qRNw22BzKwXH36K0',
    appId: '1:259265846742:web:c7da725de6de3ec95f5877',
    messagingSenderId: '259265846742',
    projectId: 'swapp-io-aa00d',
    authDomain: 'swapp-io-aa00d.firebaseapp.com',
    databaseURL: 'https://swapp-io-aa00d-default-rtdb.firebaseio.com',
    storageBucket: 'swapp-io-aa00d.firebasestorage.app',
    measurementId: 'G-15SJJHEQ6K',
  );
}
